name: install
runs:
  using: composite
  steps:
    - name: actions/checkout@v3
      uses: actions/checkout@v3
    - name: actions/setup-python@v4
      uses: actions/setup-python@v4
      with:
        python-version: |
          3.10
          3.11
        cache: pip
    - name: pip3-install
      shell: bash
      run: |
        pip3 install --upgrade pip
        pip3 install .
