name: pytest

on: [push, workflow_dispatch]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    name: Python ${{ matrix.python-version }} sample
    steps:
      - name: actions/checkout@v3
        uses: actions/checkout@v3
      - name: actions/install
        uses: ./.github/actions/install
      - name: pytest
        run: |
          pip3 install pytest
          python3 -m pytest -p no:cacheprovider
